### ISSUE TITLE
您好，邀请你加入QQ群分享micro使用心得 184572648（go micro 微服务实战）

### ISSUE THREAD

**Issue by jinbanglin** [micro-in-cn/x-gateway#3]
![image](https://user-images.githubusercontent.com/38064171/69909062-7c4e2e80-1427-11ea-9ff2-8ef066d87d60.png)

**Comment by printfcoder** [comment]
@jinbanglin 谢邀，我们暂时没有维护QQ群的计划，实在难以分心。不过建有微信群与Slack中国区：
https://github.com/micro-in-cn/Notice#%E4%BA%A4%E6%B5%81
可以大家一起维护，非常欢迎

**Comment by crazybber** [comment]
@jinbanglin 非常高兴能遇到你，同是go-micro爱好者，这里有Slack、微信群、github社区以及活跃的中文贡献者们，我们目前认为github是更适合的技术交流与分享平台，可以与全世界的贡献者们，一起coding精彩的go-micro项目，有兴趣吗? 让我们一起，[click here, we-need-you](https://github.com/micro-in-cn/Notice/blob/master/we-need-you.md) 。
